### ISSUE TITLE
Youtube update and now bot doesn't work

### ISSUE THREAD

**Issue by jdewoody71** [Just-Some-Bots/MusicBot#1313]
I noticed that youtube has changed up their interface a bit today and when I got home and sent the bot a command to play our normal gaming playlist, it crashes. Here is the error:

[Command] 175832951957749760/JDizzle (youtube playlist URL removed)
Traceback (most recent call last):
  File "/home/username/MusicBot/musicbot/bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "/home/username/MusicBot/musicbot/bot.py", line 913, in cmd_play
    numsongs = sum(1 for  in info['entries'])
  File "/home/username/MusicBot/musicbot/bot.py", line 913, in <genexpr>
    numsongs = sum(1 for  in info['entries'])
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 272, in _entries
    content_html = more['content_html']
KeyError: 'content_html'

Will there have to be a code update or is there something I need to do? Thanks!

**Comment by HellRaZoR1650** [comment]
I'm getting the same error when I use !pldump command, must be youtubes new interface or something.

**Comment by nattheraskal** [comment]
I get the same error only when I try to load playlists with 1k songs from youtube. My other playlist which only has 100 songs works though. I believe anything beyond 100 songs in a playlist results in that error.

**Comment by jdewoody71** [comment]
@nattheraskal Interesting. The playlist we use only has around 270 songs.

**Comment by jdewoody71** [comment]
Oh yeah, wanted to mention in case someone wondered, our playlist already had over 200 songs in it prior to this issue. There may be a limit but I know it isn't specifically 100 songs due to this fact. Thanks.

**Comment by ghost** [comment]
This is due to the new Youtube API Update

**Comment by mixieculez** [comment]
Might have to wait on a patch for this on youtubedl :/

**Comment by FIERCEDINO080** [comment]
Should work now, my bot was working fine yesterday and still does

**Comment by mixieculez** [comment]
@FIERCEDINO080 Same, looks like it just needed some time

**Comment by jdewoody71** [comment]
I appreciate the input but it still doesn't work. I've just started using the bot at rythmbot.co. Less hassle.
