### ISSUE TITLE
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

### ISSUE THREAD

**Issue by PolyacovYury** [Just-Some-Bots/MusicBot#1574]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Not sure if that is an issue on the bot side or the API side, but this happens really consistently. Sometimes it fully bricks the bot (it starts "playing" the songs from autoplaylist for approx. 3 seconds each and is only able to be recovered via manual restart).

### Steps to reproduce

1. Well, just install it and use normally, I guess. The issue is more likely to happen on songs with higher bitrate or longer duration. The issue is really prominent with podcasts hosted on soundcloud (e.g. [this one](https://soundcloud.com/tamrecords/neuropunk-special-the-deepspace-9-mixed-by-bes))

### Log file

```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Program Files\Python35\lib\site-packages\discord\voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1001, no reason.',)>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\discord\gateway.py", line 676, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 406, in wait_for
    return fut.result()
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Program Files\Python35\lib\site-packages\discord\voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Program Files\Python35\lib\site-packages\discord\gateway.py", line 679, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.
```

Not including the actual log file because don't really see a need in one. Noone connects to a voice channel (or a server even) when this happens. Will generate and provide one if it would be vital.

**Comment by AutumnClove** [comment]
Change your discord server region, or if you want try out the review branch.

**Comment by PolyacovYury** [comment]
Tried to change the region. Didn't work. Will try out the review branch.

**Comment by AutumnClove** [comment]
huh, odd....usually that fixes it, it's a known issue we've been having with discord WebSockets, it's not on our end rather theirs, however, the review branch has better reconnection logic to handle it, however, it is review for a reason and might still have bugs. Just a heads up.

**Comment by PolyacovYury** [comment]
The exception only occurs when the audio track is a long one. Looks like when the file is being loaded, the socket hangs up and gets destroyed. Because the short tracks don't get any errors.

There is one more error, which jumps up just as often:
```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Program Files\Python35\lib\site-packages\discord\voice_client.py:269> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Program Files\Python35\lib\site-packages\discord\voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Program Files\Python35\lib\site-packages\discord\gateway.py", line 676, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 410, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
Also crops up when playing of a long track is about to start.

**Comment by jayktaylor** [comment]
You’re correct that it’s hanging up on long tracks. This has actually been fixed in the review branch (which is super experimental right now).

You can negate this problem by turning EQ off in your config file. EQ processes the song before it plays, but it doesn’t (except in review) do it asynchronously, which is why the connection drops because the thread freezes.

**Comment by PolyacovYury** [comment]
Tried turning the experimental EQ off... and it worked! No errors on startup!
Will monitor the situation for some time, but I'm pretty sure that the problem is.. not entirely fixed, but at least negated.
Thank you very much.

**Comment by PolyacovYury** [comment]
Caught the issue which "bricks" the bot. For some bizarre reason it gets a 1006 WebSocket close code, which is not handled properly. The bot just starts iterating through autoplaylist, spending about 3 seconds on each song (even if it's an hour long) and is not able to handle even a !play command.

**Comment by AutumnClove** [comment]
This is an issue with discord and not the code really, however, review branch does handle it better and once it's pushed it should be fixed. Until then the best thing you can do is change the server region, and hard restart the bot via close the terminal and then re-running `run.bat` or `run.sh` depending on your OS.

**Comment by PolyacovYury** [comment]
Well, I do just that, but I was hoping that there is a cleaner solution to this...
Looks like the best thing I can do is give permission to `!restart` the bot to @everyone, so that ~~when~~ if it hangs up like this, people could actually restart it themselves and not blast me with messages.
Will try out the review branch when I have time. Thanks again.

**Comment by jayktaylor** [comment]
Review branch should mitigate this.
