### ISSUE TITLE
Musicbot not cycling through autoplaylist 

### ISSUE THREAD

**Issue by wellivea1** [Just-Some-Bots/MusicBot#1581]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot will play a song from the autoplaylist at startup, but then will not continue playing anything until you skip the song (it will be silent even after the song is over). Sometimes it makes the bot freeze, sometimes it will just wait for you to skip it.

### Steps to reproduce

1. Not really sure, I updated the bot and added a few more songs to my playlist and it started happening (475 songs total)
 

----
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1917840/musicbot.log)
### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by mwallis45** [comment]
I think this is a bug. if you use `restart` it should fix it up

**Comment by wellivea1** [comment]
> I think this is a bug. if you use restart it should fix it up

Well, I could use !restart every time somebody uses it, but that's not realistic. And sometimes it freezes and does not respond to any commands (including restart).

**Comment by AleanaA** [comment]
Can confirm that this is a bug. It happens to songs played using `!play` as well.

**Comment by wellivea1** [comment]
I'm not sure if this is related, but I switched server regions and it threw an error and did not play anything after. 
```
Initial autopause in empty channel
[DEBUG:bot] Serializing queue for 377511787379294208
Unpausing in Harunatsu Fansubs/Music
246571108214636544/wellivea1#7625: !skip
[DEBUG:player] Deleting file: audio_cache\youtube-8rZDCmjdb-c-BARICANG_MV.mov.webm
[DEBUG:bot] No content in current autoplaylist. Filling with new music...
[DEBUG:entry] Created future for None
Download started: https://www.youtube.com/watch?v=VC1x_RUzqq8
Download complete: https://www.youtube.com/watch?v=VC1x_RUzqq8
[DEBUG:entry] Created future for audio_cache\youtube-VC1x_RUzqq8-DENIMS_-_DAME_NA_OTONA_Official_Music_Video_Album_ver..webm
[DEBUG:bot] Serializing queue for 246586817283883008
[DEBUG:bot] Cannot delete message "", message not found
Pausing in Harunatsu Fansubs/Music (empty channel)
WARNING: Guild "Harunatsu Fansubs" changed regions: eu-west -> us-south
[DEBUG:bot] Reconnecting voice client on "Harunatsu Fansubs"
[ERROR:bot] Exception in on_guild_update
Traceback (most recent call last):
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 2864, in on_guild_update
    await self.reconnect_voice_client(after)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 422, in reconnect_voice_client
    await player.reload_voice(new_vc)
  File "C:\Users\welli\MusicBot\musicbot\player.py", line 315, in reload_voice
    self._current_player.source._resumed.clear()
AttributeError: 'NoneType' object has no attribute '_resumed'
Unpausing in Harunatsu Fansubs/Music
```

**Comment by wellivea1** [comment]
Yeah, it's crashing consistently on server change. Might be a separate bug.

```
[DEBUG:bot] Serializing queue for 246586817283883008
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021713118840] stream 0, timescale not set
WARNING: Guild "Harunatsu Fansubs" changed regions: us-south -> us-east
[DEBUG:bot] Reconnecting voice client on "Harunatsu Fansubs"
[ERROR:bot] Exception in on_guild_update
Traceback (most recent call last):
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 2864, in on_guild_update
    await self.reconnect_voice_client(after)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 422, in reconnect_voice_client
    await player.reload_voice(new_vc)
  File "C:\Users\welli\MusicBot\musicbot\player.py", line 315, in reload_voice
    self._current_player.source._resumed.clear()
AttributeError: 'NoneType' object has no attribute '_resumed'
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at C:\Users\welli\MusicBot\musicbot\player.py:318> exception=AttributeError("'VoiceChannel' object has no attribute 'server'",)>
Traceback (most recent call last):
  File "C:\Users\welli\MusicBot\musicbot\player.py", line 325, in websocket_check
    await self.voice_client.ws.ensure_open()
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 414, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\welli\MusicBot\musicbot\player.py", line 329, in websocket_check
    self.voice_client.channel.server,
AttributeError: 'VoiceChannel' object has no attribute 'server'
```

**Comment by MattBSG** [comment]
Thanks, I’ll look into it later today. Confirming, you are on latest review?

**Comment by wellivea1** [comment]
Yep.

**Comment by jayktaylor** [comment]
The issue with switching server regions should be fixed by https://github.com/Just-Some-Bots/MusicBot/commit/3a241f4c516c4e3dd9cf2ff36bbd813134d7b211, which removes our own handling of websocket disconnects (such as those caused by switching regions) and falls back to discord.py's own handling.

**Comment by wellivea1** [comment]
More errors that I didn't see before...

```
Pausing in JROCK NEWS/🎧 RADIO (empty channel)
302999297471938562/StoneGarden#8202: !play https://www.youtube.com/watch?v=cFZdRyCy5wQ
[DEBUG:bot] {'id': 'cFZdRyCy5wQ', 'uploader': 'Review3official', 'uploader_id': 'Review3official', 'uploader_url': 'http://www.youtube.com/user/Review3official', 'upload_date': '20151023', 'license': 'Standard YouTube License', 'creator': None, 'title': 'Re view 【Crossing】Music Video', 'alt_title': None, 'thumbnail': 'https://i.ytimg.com/vi/cFZdRyCy5wQ/maxresdefault.jpg', 'description': 'Re view [UNION E.P.]\nM1/ "Crossing" Music Video\n2015年9月22日発売(ライブ会場&indiesmusic.com限定)\nhttp://review3-nara.jimdo.com/\n\n奈良県発、３ピースロックバンド。\n2009年、テラモトユウイチとモトオカテル ヤスを中心に結成。\n2010年、ヨシカワユウマの加入をきっかけに、勢力的に活動を展開。\nロック/ギターロック/パワーポップ/メロ ディックパンク/エモ/ポストロックなどを巧みに取り入れた楽曲の組み立て方や、\n直情激情ロックの熱量をあくまでもクールに抑え た質感、\nほぼ日本語で歌う詞が、人間味溢れる楽曲として完成させている。\n奈良県在住。平均年齢22歳。無所属。読み方は"リビ ュー"。\nこれまでにデモCDを2枚、宇都宮tactとのスプリットデモCD1枚を制作。インディーズレーベル主催のオムニバスアルバムにも多数参加。\n2013年、2曲入りフリーデモ【Love me two times】を会場限定で配布開始。\n2014年7月26日には約3年振りとなる単独デモCD、\n【Pabulum e.p.】をライブ会場&indiesmusic.com限定で発売し、\n2014年7月26日心斎橋新神楽での自主企画を皮切りに全44本の全国ツアーを敢行。\n同年11月15日、地元奈良NEVER LANDでツアーファイナルを行う。\n現在、年間100本近くのライブを重ねながら、 奈良•大阪を中心に全国各地で活動中。', 'categories': ['Music'], 'tags': ['奈良', 'バンド', 'Re view', 'PV', 'MV', 'リビュー', 'りびゅー', 'なら', 'Re view バンド', 'Re view 奈良 PV', 'Re view 奈良 MV', 'Re view 奈良 バンド', 're view バンド', 're view 奈良', 'Re view 奈良', 'review 奈良 バンド', 'Pabulum e.p.', 'Pabulum', 'UNION E.P.', '奈良 バンド'], 'subtitles': {}, 'automatic_captions': {}, 'duration': 263, 'age_limit': 0, 'annotations': None, 'chapters': None, 'webpage_url': 'https://www.youtube.com/watch?v=cFZdRyCy5wQ', 'view_count': 30476, 'like_count': 171, 'dislike_count': 5, 'average_rating': 4.88636350632, 'formats': [{'format_id': '249', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465365791759&requiressl=yes&clen=1645088&mime=audio%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&keepalive=yes&source=youtube&ipbits=0&signature=69424CFD7C0AEF9661D8ECAD36169CA592F6198F.53518DF9FDCDE10680F35E5E8A77C5A9CC3B65B7&itag=249&key=yt6&gir=yes&expire=1524237195&dur=262.601&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'format_note': 'DASH audio', 'acodec': 'opus', 'abr': 50, 'filesize': 1645088, 'tbr': 58.746, 'vcodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '250', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465366898786&requiressl=yes&clen=2196801&mime=audio%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&keepalive=yes&source=youtube&ipbits=0&signature=9223E9590341EE5DA83020BD77EB8F59FF4EB1F0.C089AA19CD2594B6DACBC6260E5E95D17BC4E4B2&itag=250&key=yt6&gir=yes&expire=1524237195&dur=262.601&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'format_note': 'DASH audio', 'acodec': 'opus', 'abr': 70, 'filesize': 2196801, 'tbr': 81.162, 'vcodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '140', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457866888901453&requiressl=yes&clen=4172446&mime=audio%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&keepalive=yes&source=youtube&ipbits=0&signature=4319C51E7B779C559F5CF4B86DB14D64F44D8631.9B073BB032481ADB7AA4C3F7AE92D3964C9886CA&itag=140&key=yt6&gir=yes&expire=1524237195&dur=262.664&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'm4a', 'format_note': 'DASH audio', 'acodec': 'mp4a.40.2', 'abr': 128, 'container': 'm4a_dash', 'filesize': 4172446, 'tbr': 128.056, 'vcodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '171', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465367808969&requiressl=yes&clen=4049497&mime=audio%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&keepalive=yes&source=youtube&ipbits=0&signature=C7C0231CC79332B6063EC0F617147B8020D95BBD.2C9AF0408BA47FA024CAB566F4CC7ED188CF8835&itag=171&key=yt6&gir=yes&expire=1524237195&dur=262.596&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'acodec': 'vorbis', 'format_note': 'DASH audio', 'abr': 128, 'filesize': 4049497, 'tbr': 133.645, 'vcodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '251', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465367638034&requiressl=yes&clen=4301132&mime=audio%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&keepalive=yes&source=youtube&ipbits=0&signature=58B9728986BA5D89FBD62D730DF38FDEAC518B47.4793B051AC81451E88F0D8256F5C982772352E6D&itag=251&key=yt6&gir=yes&expire=1524237195&dur=262.601&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'format_note': 'DASH audio', 'acodec': 'opus', 'abr': 160, 'filesize': 4301132, 'tbr': 153.768, 'vcodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '278', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465720809147&requiressl=yes&clen=2786743&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=CD9D2F27268646B1D12F0968BA8DFBA53C7D4269.04CE67A4C97F04D29C7859FEE2D67E2AA782898C&itag=278&key=yt6&gir=yes&expire=1524237195&dur=262.512&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 144, 'format_note': '144p', 'container': 'webm', 'vcodec': 'vp9', 'filesize': 2786743, 'tbr': 111.49, 'width': 256, 'fps': 12, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '160', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867369534784&requiressl=yes&clen=3633492&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=8C77369D3F0CFD59DFD062F92F5CBCE3DBCE6890.3743896E366C3972F676E232D919F4D8C4F2EF0C&itag=160&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 144, 'format_note': '144p', 'vcodec': 'avc1.4d400c', 'filesize': 3633492, 'tbr': 117.49, 'width': 256, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '133', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867369434442&requiressl=yes&clen=8137826&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=9F3B4558E0065AF631E468EBCB7600AECF94410D.C3D97FC9E54A416E5CC139C5F2206CF06651CF47&itag=133&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 240, 'format_note': '240p', 'vcodec': 'avc1.4d4015', 'filesize': 8137826, 'tbr': 260.812, 'width': 426, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '242', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465718097561&requiressl=yes&clen=5174408&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=589C409C1BBCFEE4CBB82FDA0CBE36917E836BE2.59D990FBD90F132FA2FFB40FFBFA473277524A88&itag=242&key=yt6&gir=yes&expire=1524237195&dur=262.554&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 240, 'format_note': '240p', 'vcodec': 'vp9', 'filesize': 5174408, 'tbr': 260.958, 'width': 426, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '243', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465718373859&requiressl=yes&clen=10009841&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=CBE9E8E6559CB4B42876F03444F4FF075F0C588E.75B81565B076326EC28B69C81E333FB185F616A4&itag=243&key=yt6&gir=yes&expire=1524237195&dur=262.554&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 360, 'format_note': '360p', 'vcodec': 'vp9', 'filesize': 10009841, 'tbr': 500.024, 'width': 640, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '134', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867369888732&requiressl=yes&clen=10134456&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=5AB9861D05A03B403F635E115EEF9398D895507A.02A39FD122D562829E40A7BDBA09E09161EB1C05&itag=134&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 360, 'format_note': '360p', 'vcodec': 'avc1.4d401e', 'filesize': 10134456, 'tbr': 513.729, 'width': 640, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '244', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465721099409&requiressl=yes&clen=17853980&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=2907A4658161C69B20457428F19046345C64D2B7.D0DF9C21F5D30DF7A9EFFD94B04F36E497CEC39B&itag=244&key=yt6&gir=yes&expire=1524237195&dur=262.554&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 480, 'format_note': '480p', 'vcodec': 'vp9', 'filesize': 17853980, 'tbr': 874.731, 'width': 854, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '135', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867370141361&requiressl=yes&clen=21706350&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=41B10B92A970AB4A180816B2EA77520D7D9E5571.038DFF91FB6B2C245CE87BE0707A44DF4866374D&itag=135&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 480, 'format_note': '480p', 'vcodec': 'avc1.4d401e', 'filesize': 21706350, 'tbr': 1074.659, 'width': 854, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '247', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465722886390&requiressl=yes&clen=36492519&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=0651D19F1ABF36E924B1FD9C966E5000C2CE1AA3.DD6ED7A7D723E6CBF5F9464D27C048F4813D0903&itag=247&key=yt6&gir=yes&expire=1524237195&dur=262.554&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 720, 'format_note': '720p', 'vcodec': 'vp9', 'filesize': 36492519, 'tbr': 1664.023, 'width': 1280, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '136', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867371085915&requiressl=yes&clen=42038605&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=BFB5A9E215219096F6FC395214031546269C299F.37CE01463EF682504B32091E4357D1374F3FC5FC&itag=136&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 720, 'format_note': '720p', 'vcodec': 'avc1.4d401f', 'filesize': 42038605, 'tbr': 1959.52, 'width': 1280, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '248', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465636625945&requiressl=yes&clen=66788609&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=69394F05BDE38D646DD75538295F7052F35F8736.C69FB63C58B2D4CBF102BB2B6C9DACB6D97094D0&itag=248&key=yt6&gir=yes&expire=1524237195&dur=262.554&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'height': 1080, 'format_note': '1080p', 'vcodec': 'vp9', 'filesize': 66788609, 'tbr': 3013.2, 'width': 1920, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '137', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457867078648969&requiressl=yes&clen=75998973&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&keepalive=yes&source=youtube&ipbits=0&signature=1DAA463C240D6F7200C5456516FFCC9BFA582CB0.DD26062CB05F496D6E973DF62C52D5CF200858AA&itag=137&key=yt6&gir=yes&expire=1524237195&dur=262.595&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'height': 1080, 'format_note': '1080p', 'vcodec': 'avc1.640028', 'filesize': 75998973, 'tbr': 3451.182, 'width': 1920, 'fps': 24, 'acodec': 'none', 'downloader_options': {'http_chunk_size': 10485760}}, {'format_id': '17', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442464548794207&requiressl=yes&clen=2590589&mime=video%2F3gpp&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&source=youtube&ipbits=0&signature=9ADB472FBAD3B3F15B4000C510FF5D214D5DDEC5.8394594FA9A8406B8E35E60BD948CEE9643E7345&itag=17&key=yt6&gir=yes&expire=1524237195&dur=262.710&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': '3gp', 'width': 176, 'height': 144, 'acodec': 'mp4a.40.2', 'abr': 24, 'vcodec': 'mp4v.20.3', 'resolution': '176x144', 'format_note': 'small'}, {'format_id': '36', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442464551501993&requiressl=yes&clen=7209135&mime=video%2F3gpp&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&source=youtube&ipbits=0&signature=9022C2D92868FBF1765FE5C273ACF0546BCF737D.4384097D88E81D6773EC94CC69475B717DE4731A&itag=36&key=yt6&gir=yes&expire=1524237195&dur=262.710&pl=21&ratebypass=yes', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': '3gp', 'width': 320, 'acodec': 'mp4a.40.2', 'vcodec': 'mp4v.20.3', 'resolution': '320x180', 'height': 180, 'format_note': 'small'}, {'format_id': '43', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1442465421287878&requiressl=yes&clen=24437508&mime=video%2Fwebm&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&source=youtube&ipbits=0&signature=0E479F8C7110EC35DB4021D44C609AED606964F0.63E627D74092DB2386A9A9C179905C767E693E9B&itag=43&ratebypass=yes&gir=yes&expire=1524237195&key=yt6&dur=0.000&pl=21', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'webm', 'width': 640, 'height': 360, 'acodec': 'vorbis', 'abr': 128, 'vcodec': 'vp8.0', 'resolution': '640x360', 'format_note': 'medium'}, {'format_id': '18', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?c=WEB&ip=45.25.108.213&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&initcwndbps=897500&fvip=3&lmt=1457866757449745&requiressl=yes&clen=15477278&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&source=youtube&ipbits=0&signature=5751BFB36C6C95367AF3A76E5DE14329D11D0B0E.8234E32C94ABFC282432ADB0C9A2B78C3D9CA40B&itag=18&ratebypass=yes&gir=yes&expire=1524237195&key=yt6&dur=262.664&pl=21', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'width': 640, 'height': 360, 'acodec': 'mp4a.40.2', 'abr': 96, 'vcodec': 'avc1.42001E', 'resolution': '640x360', 'format_note': 'medium'}, {'format_id': '22', 'url': 'https://r3---sn-5uaeznys.googlevideo.com/videoplayback?ratebypass=yes&ip=45.25.108.213&ipbits=0&signature=DB571E7EF9BDEC7E164D749D3F18B0687672D7C2.A39ECBE57C15707376BFB45725854453D3A06BEF&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-AGbJ3nPnRl-R1hL53dV8QHktrHLozNSlvAB5hxBjdryu&ei=K6_ZWsaRH9WhqwWk7LuYCg&itag=22&initcwndbps=897500&fvip=3&lmt=1472279045709902&requiressl=yes&key=yt6&mime=video%2Fmp4&mn=sn-5uaeznys%2Csn-q4f7sn76&mm=31%2C26&ms=au%2Conr&mv=m&mt=1524215499&expire=1524237195&dur=262.664&pl=21&source=youtube&c=WEB', 'player_url': '/yts/jsbin/player-vflFcxzRO/en_US/base.js', 'ext': 'mp4', 'width': 1280, 'height': 720, 'acodec': 'mp4a.40.2', 'abr': 192, 'vcodec': 'avc1.64001F', 'resolution': '1280x720', 'format_note': 'hd720'}], 'is_live': None, 'start_time': None, 'end_time': None, 'series': None, 'season_number': None, 'episode_number': None, 'extractor': 'youtube', 'webpage_url_basename': 'watch', 'extractor_key': 'Youtube'}
[DEBUG:entry] Created future for None
[DEBUG:bot] Serializing queue for 221961004614025217
Download started: https://www.youtube.com/watch?v=cFZdRyCy5wQ
Download complete: https://www.youtube.com/watch?v=cFZdRyCy5wQ
Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000024F8D565518>
transport: <_ProactorSocketTransport fd=1424>
Traceback (most recent call last):
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\proactor_events.py", line 190, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\windows_events.py", line 702, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\windows_events.py", line 442, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
Unpausing in NEGU/Music
Unpausing in JROCK NEWS/🎧 RADIO
Pausing in JROCK NEWS/🎧 RADIO (empty channel)

Reconnected to discord.

Unpausing in Harunatsu Fansubs/Music
Pausing in Harunatsu Fansubs/Music (empty channel)
Unpausing in JROCK NEWS/🎧 RADIO
246571108214636544/wellivea1#7625: !skip
[DEBUG:player] Deleting file: audio_cache\generic-RADWIMPS-_____-original-ver.-RADWIMPS-_-original-ver.-531753d0.m4a
[DEBUG:entry] Created future for audio_cache\youtube-cFZdRyCy5wQ-Re_view_Crossing_Music_Video.webm
[DEBUG:bot] Serializing queue for 221961004614025217
[DEBUG:bot] Serializing queue for 221961004614025217
Pausing in JROCK NEWS/🎧 RADIO (empty channel)

Reconnected to discord.

Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000024F8D23A3C8>
transport: <_ProactorSocketTransport fd=936>
Traceback (most recent call last):
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\proactor_events.py", line 190, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\windows_events.py", line 702, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\welli\AppData\Local\Programs\Python\Python36\lib\asyncio\windows_events.py", line 442, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
Unpausing in Kami-Fansubs/Music
Unpausing in Harunatsu Fansubs/Music
Pausing in Harunatsu Fansubs/Music (empty channel)
Unpausing in Harunatsu Fansubs/Music
246571108214636544/wellivea1#7625: !skip
[DEBUG:player] Deleting file: audio_cache\youtube-j98-yxQe-lc-DADARAY.webm
[DEBUG:bot] No content in current autoplaylist. Filling with new music...
[DEBUG:entry] Created future for None
Download started: https://www.youtube.com/watch?v=ZY78asVr0CI
Download complete: https://www.youtube.com/watch?v=ZY78asVr0CI
[DEBUG:entry] Created future for audio_cache\youtube-ZY78asVr0CI-Ellie_Goulding_-_Wish_I_Stayed_Acoustic.webm
[DEBUG:bot] Serializing queue for 246586817283883008
```

**Comment by wellivea1** [comment]
Has anybody found out what causes this (the freezing after one song)? The bot is pretty much unusable in this state, so I might have to switch back to master. I'd prefer testing out all the new features of review, etc though.

**Comment by AleanaA** [comment]
Review is full of bugs and issues and shouldn't be used for daily use aside from testing. It's advised that you use the Master branch, and wait for Review to be merged, as issues like this, and many others are bound to occur, especially since the bot is moving over to the d.py rewrite.

**Comment by wellivea1** [comment]
I never really had issues that made it totally unusable, maybe certain features not working (like search, etc). And how else are you going to test open source software other than having people use it for daily use? I totally understand that these issues are unavoidable though, just wanted to know if there was any progress.

**Comment by OzzyHelix** [comment]
I do hope that a resolution can be found quickly

**Comment by wallopthecat** [comment]
How can I debug this?

**Comment by jayktaylor** [comment]
Should be fixed, thanks guys 👍

**Comment by wellivea1** [comment]
Not fixed for me. Well, it seems to not be loading the autoplaylist at all now (only one time then it stops).
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1993894/musicbot.log)

**Comment by jayktaylor** [comment]
Can you send a copy of your autoplaylist? Also, are you using a modified version of the bot? The versioning in your log file does not correspond to one of our releases.

**Comment by wellivea1** [comment]
It's not really modified, the name in the constants file is just changed for consistency (and the profile image in the responses). Here's the autoplaylist:
[autoplaylist.txt](https://github.com/Just-Some-Bots/MusicBot/files/1997130/autoplaylist.txt)

**Comment by wellivea1** [comment]
Getting this rather than a coherent response when using !play outside voice.
```
Traceback (most recent call last):
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 2589, in on_message
    await self._check_ignore_non_voice(message)
  File "C:\Users\welli\MusicBot\musicbot\bot.py", line 329, in _check_ignore_non_voice
    if not vc or vc == msg.author.voice.channel:
AttributeError: 'NoneType' object has no attribute 'channel'
```
And still not getting any autoplaylist after skipping if I update and override my naming changes
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2037464/musicbot.log)

**Comment by AutumnClove** [comment]
Please do a git pull to update

**Comment by wellivea1** [comment]
It stopped giving the error when using !play, but it's still not starting the autoplaylist.

**Comment by wellivea1** [comment]
I did git pull and through update.bat. It's still no use.

**Comment by AleanaA** [comment]
Providing new logs and your autoplaylist for this would be appreciated. I've tested the new updates and the autoplaylist works fine, unless you've disabled `SaveVideos`.

**Comment by wellivea1** [comment]
It's not playing anything, including the autoplaylist with the latest update. Here's the logs.
[autoplaylist.txt](https://github.com/Just-Some-Bots/MusicBot/files/2153628/autoplaylist.txt)
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2153629/musicbot.log)

**Comment by wellivea1** [comment]
SaveVideos is disabled. Is this an issue?

**Comment by wellivea1** [comment]
I'll try to play something, then it will act like it added it to an existing queue, then it plays nothing. And the np command will show this: https://i.imgur.com/6wLxdbf.png https://i.imgur.com/cSjmXyV.png

**Comment by wellivea1** [comment]
This definitely hasn't been resolved so I'm not sure why the issue is closed... Unless I'm doing something wrong (doubt it). ¯\_(ツ)_/¯

**Comment by AleanaA** [comment]
Out of curiosity, does git pull run successfully or does it error? If it runs successfully, does a fresh install of review work fine? As of now, the only issue I've seen with playing anything, is with SaveVideos turned off, outside of that, it works fine. If turning that setting on fixes the issue, I'd recommend making a new issue regarding that.

**Comment by wellivea1** [comment]
Git pull runs without error and I tried doing everything over before. I changed the setting and updated the bot again. I'll check everything tomorrow
