### ISSUE TITLE
Playing Spotify Playlist URIs Not Working [Even After (https://github.com/Just-Some-Bots/MusicBot/commit/8fad33263e7ba4f981d53a347efb292e13c201f3)]

### ISSUE THREAD

**Issue by HaydenJM** [Just-Some-Bots/MusicBot#1710]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)

What type of issue are you creating?

- [x] [Bug]

----

### Description of issue

Attempting to play Spotify playlist URIs using the 'play' command returns `Exception in on_message`

Full Error:

```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 2705, in on_message
    response = await handler(**handler_kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 1311, in cmd_play
    res['tracks']['items'].extend(resp['tracks']['items'])
KeyError: 'tracks'
```

### Steps to reproduce

1. Use the 'play' command followed by any Spotify playlist URI

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2326665/musicbot.log)

**Comment by AutumnClove** [comment]
I'm on mobile, and as such can't view the log, could you please provide the uri you used, looking at this quickly I suspect you are subject to using url instead of uri

**Comment by HaydenJM** [comment]
The Spotify URI that I used was `spotify:user:alltrapnation:playlist:0NCspsyf0OS4BsPgGhkQXM`

Using the same URI with "Dyno Bot" seems to work just fine.

**Comment by jayktaylor** [comment]
@AmiT177 fancy looking into this?

**Comment by amit177** [comment]
I noticed that when the amount of tracks is 100+ and it's not even (100. 200. 300...) the keys in the dict are different. Doing some debugging right now.

**Comment by AutumnClove** [comment]
This should now be fixed

**Comment by SonixApache** [comment]
Still an issue.
Using URI `spotify:user:bezoing:playlist:71yNeiFbb8bDhgLIzu9eae`, which has 178 tracks, the same error occurs.
```python
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "\MusicBot\bot.py", line 2705, in on_message
    response = await handler(**handler_kwargs)
  File "\MusicBot\bot.py", line 1311, in cmd_play
    res['tracks']['items'].extend(resp['tracks']['items'])
KeyError: 'tracks' 
```

Python 3.7, bot version `1.9.8`, all dependencies updated today.

**Comment by amit177** [comment]
The fix for the issue wasn't merged yet, it's still in the review branch.

**Comment by SonixApache** [comment]
Right, I see. Checked the wrong commit, sorry.

**Comment by MattBSG** [comment]
If for whatever reason review was not a fix for you, please reopen
