### ISSUE TITLE
AutoPause Fix

### ISSUE THREAD

**Issue by Daztek** [Just-Some-Bots/MusicBot#1785]
Hey, 

AutoPause is currently broken due to a bug on line [2813 in bot.py](https://github.com/Just-Some-Bots/MusicBot/blob/a7c8ed067de278b0625dd6d8f35f3653a0755b82/musicbot/bot.py#L2813)

`if len(player.voice_client.channel.members) == 0:` 

should be

`if len(player.voice_client.channel.members) == 1:`

since the bot itself counts as a member too.

**Comment by AutumnClove** [comment]
There's a PR for a fix for this which hasn't been merged yet, thank you for the feedback
-sent from my Android

**Comment by LazoYoung** [comment]
Any news on the fix? I can't find any PR for this

**Comment by LazoYoung** [comment]
@Daztek That shouldn't be problem since the script checks whether user is not the bot itself in [this line](https://github.com/Just-Some-Bots/MusicBot/blob/a7c8ed067de278b0625dd6d8f35f3653a0755b82/musicbot/bot.py#L2801)

**Comment by MattBSG** [comment]
Fix was pushed to review

**Comment by AutumnClove** [comment]
Sorry for the false information, the PR didn't fix this, it was merged in but it didn't address this.
