### ISSUE TITLE
Owner not found in a voice channel

### ISSUE THREAD

**Issue by Pause516** [Just-Some-Bots/MusicBot#369]
I updated my bot and I was given this error. So I re-downloaded it and copied my config file. Nothing, same error

**Comment by Piduino** [comment]
This just started happening to me too. I found that having it set to auto join a channel is a quick workaround.

**Comment by Pause516** [comment]
Do I input my user or is there a channel id? If so, how to I get my channel's id?

**Comment by Piduino** [comment]
```
; Join a channel on startup.  Multiple channels can be added for multiple servers. Remember, use IDs, not names.
; If both this option and AutoSummon are enabled, this option takes priority.
;
AutojoinChannels = 0000000000000000
;
```

Uncomment the autojoinchannels like I did, then go to discord > appearance > enable dev mode. Right click on the channel and "copy id". Now the bot should auto-join that channel when it is launched and no need for the !summon command. Also I was getting errors from other users that they could not request music and joining/leaving the room and coming back seemed to fix it.

**Comment by Pause516** [comment]
Thank you so much!!! Worked 100%!!

**Comment by Benjoi4231** [comment]
This did not work for me, I am still getting the same problem

**Comment by dfarley1** [comment]
I'm having the same issue, and AutoJoinChannels did not fix it.

**Comment by jayktaylor** [comment]
**Resolved.** This is fixed in version `1.9.5_2`. Update your bot, then update your dependencies.

**Comment by PapaLeaf** [comment]
Ah yes this does not work for me. I'm new to this whole thing but i followed a video and i still get the issue Owner not found
